name: ci

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set Up Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.3'
      -
        name: Checkout
        uses: actions/checkout@master
      -
        name: Get Dependencies
        run: go mod download
      -
        name: Build
        run: CGO_ENABLED=0 GOOS=linux go build -o bin/sentry-exporter
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sentry-exporter
          path: bin/sentry-exporter
  docker:
    needs: [go]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: maggotmouth/sentry-exporter
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: sentry-exporter
          path: bin/sentry-exporter
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
